sudo: required

services:
  - docker

before_install:
  - docker build -t morgenes23/test-php-docker-travis -f app.dockerfile .

script:
  - docker run morgenes23/docker-react npm run test -- --coverage