sudo: required

services:
  - docker

before_install:
- docker build -t morgenes23/php-docker-travis .

#script:
#  - docker run morgenes23/test-php-docker-travis
after_success:
  - docker build -t morgenes23/php-docker-travis .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push morgenes23/php-docker-travis

deploy:
  provider: elasticbeanstalk
  on:
    branch: master
  region: "us-east-2"
  app: "php-docker-travis"
  env: "PhpDockerTravis-env"
  bucket_name: elasticbeanstalk-us-east-2-218183310905
  bucket_path: "php-docker-travis"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"


